# Characteristics of the pipe and the effluent flow
[pipe]
time = [1970-01-01]
flow = [0.2]
dens = [1000]
diam = [0.5]
depth = [100]
decline = [0]

# Characteristics of the ambient water masses
[ambient]
time = [1970-01-01]
depth = [100]
coflow = [[0]]
crossflow = [[0]]
dens = [[1000]]

# Output options
[output]
csv.file = "out.csv"
trajectory.step = 1           # Time between trajectory points [s]
trajectory.stop = 4           # Time of final trajectory point [s]
release.start = 1970-01-01    # Time of first release [date]
release.stop = 1970-01-01     # Time of final release [date]
release.step = 3600           # Time between releases [s]
